Algoritmo "Meu Primeiro Algoritmo"
// Disciplina  :  [Linguagem e Lógica de Programação] 
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Gustavo Santos
// Data atual  : 17/04/2020
Var
// Seção de Declarações das variáveis 
    nota: real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
               nota <- 100/4
               escreva("Resultado: ", nota)

Fimalgoritmo